### ISSUE TITLE
Floats should be accepted

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/PhysWikiQuiz#3]
![Screenshot 2021-08-30 at 08-59-30 PhysWikiQuiz](https://user-images.githubusercontent.com/2777736/131298687-7a3bb201-5a7c-46e2-90cb-b880f7420782.png)

**Comment by philsMINT** [comment]
tolerance +- 1%

**Comment by physikerwelt** [comment]
![Screenshot 2021-09-03 at 09-33-02 PhysWikiQuiz](https://user-images.githubusercontent.com/2777736/131967910-a8855816-c450-43a5-b545-812912fe7f80.png)
In practice the tolerance is greater than 1%. Can you elaborate?

**Comment by philsMINT** [comment]
0.1/16 = 0.0625 = 0.625%
