### ISSUE TITLE
problem with Q159241 and translation offer

### ISSUE THREAD

**Issue by SimonVilleneuvewp** [ag-gipp/PhysWikiQuiz#6]
Hi,

Very nice ! Thank you for this work. If you want, I can translate in French the site.

I've try to adapt the direct current item (Q159241). The unit is ok, but not the value and I don't understand why.
<img width="347" alt="direct current" src="https://user-images.githubusercontent.com/22546062/138949495-e1ed35f3-6034-4fb0-a1ef-5ca7ad7b5fbc.png">

**Comment by philsMINT** [comment]
I think it works now? Doesn't it?

By the way: Are you employing the system somewhere (in teaching) or just playing for fun?

**Comment by SimonVilleneuvewp** [comment]
super !

I think it's too soon to use it in teaching. If I present it now to my colleagues, they'll probably reject it (in English, many items didn't work, minimalist interface, etc.). But yes, my goal is to use it in class with students in cegep (about 17 to 20 years old, equivalent to last year in high school/first year of university).

**Comment by philsMINT** [comment]
Sounds great!

I just read your text on PhysWikiQuiz.
There are not just 10 questions supported but in principle infinite. You only need to edit the existing Wikidata items from physics listed at https://w.wiki/3zt9 or create new concept items. We are working on making more and more examples compatible. PhysWikiQuiz has several dependencies, Wikidata, LaCASt, Sympy, etc., potentially making problems to be tackled.

**Comment by SimonVilleneuvewp** [comment]
I corrected(https://fr.wikipedia.org/w/index.php?title=Wikip%C3%A9dia:RAW/2021-11-01&diff=187608979&oldid=187608836)

See Ya !

**Comment by SimonVilleneuvewp** [comment]
Me again,

Your edits on alternating current has been reverted ([https://www.wikidata.org/w/index.php?title=Q124164&diff=next&oldid=1519563360&diffmode=source])

Can you adapt the tool to adjust to vector and derivative/integral quantities ?

**Comment by philsMINT** [comment]
No problem, it should work now. By the way, I introduced a new teacher/student view switch.

**Comment by SimonVilleneuvewp** [comment]
nice !

Thanks again. I'll check from time to time the evolution of your tool.

**Comment by SimonVilleneuvewp** [comment]
Do you think you can transform the slash in units answers? like the tool recognize "m/s" in "m s^-1" by transforming "/s" by "s^-1" ?

**Comment by philsMINT** [comment]
Thank you very much for the additional suggestion.

All kinds of variations of the unit should be accepted now, e.g.,
![grafik](https://user-images.githubusercontent.com/34623854/141153327-04a0b8ba-5eaa-4121-897e-4f75fd108274.png)

If not please open a separate issue.
Also please separately for any other kind of further suggestion, very much appreciated.

We now provide an API for question generation, e.g., https://physwikiquiz.wmflabs.org/api/v1?name=speed
If you demonstrate / employ / advertise the system somewhere, we would be happy to be notified :)

**Comment by SimonVilleneuvewp** [comment]
Ok, I'll create new "issues" for further suggestions.

The "teacher/student" interface have disapeared. Is it normal doctor ?

I'll speak to collegues in maths to see if they are interested about this.

**Comment by philsMINT** [comment]
For me the "teacher/student" switch still works. If the problem persists for you, let me know.

Thanks!
